travis:
  secure:
    BINSTAR_TOKEN: bFvhdhnQhyWEJxRBJS9HXy0/ML2WtAqfEWibYq+Nytu0qdqLJcX7GW5tBunbG5BwB1AkyEPBtrEfQwiHqd5GfWbTr24xVJw+yv/7ADXR2Y5lm7PFH0VmDrvJf5ccDSP+D9FA9yABYb332+juMRf9fMnJHLRybV9cesDKJqRb2F38ZCja7kSw8D5rcoOGmvGYc216eY2l7JANbfPjXm7NynCLf3TJ65tZbPCDWFc+tGJmNQeUPwaqkuVvcUAV3R10rpvFRlQl+W7sQuer3Ccs6cIxpyqJ2CCrRJBDuIzdURB5K+y8YTiw5RcUE2ImopqxujKqF6lnaFXMdq3a+NEy4qmVoKdQc43O0mE9IZDi4qlbcJw8mofx//gCnYPI+ghgZ2wks+2bG07x3UeJ16Kp1v8QkgFBm2Wfu0h7IBZxRupN7HVdkSYkwQP6DczcHqmSKq/V6WYJHOHtl2fj31GeT9tISu9mSZgLN09KaaqbpAmsVdVIYRVZIOoKhsE8ZL0BNu2YvPcDOxTIf5HRN7haqcVisXGvN6jVuH8aCiRO4HWgBN4DAAoH3F0eJr1wEXRYAmfewHVvwcxJuQ48NkgnzbASgtfPjr7cBl8hk6l7c+7XgI+rSg4AOe+C+JK8pPTktIsJF4CncyOnYgN+si92/TXqJN8/KCU3oriQiI46kRs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
